### ISSUE TITLE
Restrict requesting same article multiple times

### ISSUE THREAD

**Issue by karllhughes** [draftdev/writer-portal#13]
Some writers have mistakenly requested the same article multiple times. I'm not sure how this happens exactly, but probably a timing bug. We should restrict this if possible.

**Comment by karllhughes** [comment]
I'm testing this out and can't figure out how writers are able to do this. It seems like I cannot request the same article multiple times.

**Comment by karllhughes** [comment]
Actually, this is a bit more complicated.

The only way to make duplicate requests is to catch the database in a non-updated state. Since Airtable/Postgres take ~5 seconds to sync, there's a window where you can refresh and request the same article twice.

Probably not going to fix this right away as that's pretty tough to solve, but I'll leave the issue open for further comment.

**Comment by KSiig** [comment]
@karllhughes Couldn't this be solved in a simple, albeit quite ugly, way, by saving an object in localstorage with all the requested articles, and then check that before sending the request to the backend?

**Comment by karllhughes** [comment]
@KSiig that would probably work, but introducing caching is a surefire way to introduce new hard-to-diagnose bugs. Especially in localstorage because we have no access to it and it's kind of hard for users to clear.

I may ask SyncInc about this and see why this refresh time is so long and if we can shorten it.

**Comment by heraldofsolace** [comment]
This is fixed after one year.

For the curious, because Airtable restricts to only 5 API calls in a second, there's a slight delay in Sequin sync. When the request is updated via the Sequin proxy, Sequin updates it in both the database and Airtable, but doesn't update any linked records. So the linked assignment record was only updated via the normal (delayed) sync.

In the new release, we manually update the linked record and also cache the result locally.
